name: selector_train
network: selector
selector_angle_num: 5
worker_num: 8
##########loss##############
loss: [selection_loss]
val_metric: [vis_sel]
key_metric_name: sel_ang_acc
#没啥用
output_interval: 15

###########dataset##########
train_dataset_type: sel_finetune
train_dataset_cfg:
  use_database_sample_prob: true
  database_sample_prob: [   10  ]
  #scy:其实应该是database_set_names
#  database_names: [   'linemod_train'  ]
  database_names: [   'co3dv2_finetune'  ]

  batch_size: 16
  ref_type: fps_64

  use_render: false
  resolution: 128
  reference_num: 128

  selector_scale_range: [-0.3, 0.3]
  selector_angle_range: [-90, 90]
  selector_angles: [-90, -45, 0, 45, 90]
  # selector_real_aug: true scy
  selector_real_aug: false

val_set_list:
  -
    name: cat_val
    type: sel_val
    cfg:
      # ref_database_name: linemod/cat
      # test_database_name: linemod/cat
      ref_database_name: linemod/ape
      test_database_name: linemod/ape
#      ref_database_name: co3dv2/ape
#      test_database_name: co3dv2/ape

      ref_split_type: linemod_val
      test_split_type: linemod_val
      selector_angles: [-90, -45, 0, 45, 90]
      selector_ref_num: 128
      selector_ref_res: 128
  # -
  #   name: warrior_val
  #   type: sel_val
  #   cfg:
  #     ref_database_name: genmop/tformer-ref
  #     test_database_name: genmop/tformer-test
  #     ref_split_type: all
  #     test_split_type: all
  #     selector_angles: [-90, -45, 0, 45, 90]
  #     selector_ref_num: 64
  #     selector_ref_res: 128

##########optimizer##########
# optimizer_type: adam
optimizer_type: sgd
lr_type: exp_decay
lr_cfg:
  # lr_init: 1.0e-4 before D
  # decay_step: 100000 before D
#  lr_init: 1.0e-2
  lr_init: 1.0e-3
  # lr_init: 1.0e-4
  # decay_step: 2000 D2
  # decay_step: 1000
  decay_step: 5000

  #
  decay_rate: 0.5
  #################################scy add################################
  scy_base_step: 270000
  confidence_module_lr__factor: 1.2
  # weight_decay: 0
  weight_decay: 1.0e-6
  ################################ END ################################
# total_step: 300000
total_step: 330000
# train_log_step: 50
# val_interval: 5000
# save_interval: 500
train_log_step: 5
val_interval: 3000
# val_interval: 800
save_interval: 900